# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "scsi_defs"
edition = "2021"
rust-version.workspace = true

[dependencies]
zerocopy.workspace = true
bitfield-struct.workspace = true
open_enum.workspace = true
arbitrary = { workspace = true, features = ["derive"] }

[lints]
workspace = true
